site_name: UCI Nature Wildlife Pipeline
site_description: Backend pipeline documentation for UCI Nature.
site_url: https://ralkhleef.github.io/UCI-NATURE/

theme:
  name: material
  font: false
  palette:
    - scheme: default
      primary: blue
      accent: green
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Setup: setup.md
  - Run: run.md
  - Troubleshooting: troubleshooting.md

plugins:
  - search

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences


docs_dir: docs
site_dir: site
